#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Boulot.Resource", IsApplication=true)]

namespace Boulot
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010010
			public const int ambientEnabled = 2130771984;
			
			// aapt resource value: 0x7f01001a
			public const int buttonSize = 2130771994;
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010012
			public const int cameraMaxZoomPreference = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int cameraMinZoomPreference = 2130771985;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f010019
			public const int circleCrop = 2130771993;
			
			// aapt resource value: 0x7f01001b
			public const int colorScheme = 2130771995;
			
			// aapt resource value: 0x7f010018
			public const int imageAspectRatio = 2130771992;
			
			// aapt resource value: 0x7f010017
			public const int imageAspectRatioAdjust = 2130771991;
			
			// aapt resource value: 0x7f010015
			public const int latLngBoundsNorthEastLatitude = 2130771989;
			
			// aapt resource value: 0x7f010016
			public const int latLngBoundsNorthEastLongitude = 2130771990;
			
			// aapt resource value: 0x7f010013
			public const int latLngBoundsSouthWestLatitude = 2130771987;
			
			// aapt resource value: 0x7f010014
			public const int latLngBoundsSouthWestLongitude = 2130771988;
			
			// aapt resource value: 0x7f010006
			public const int liteMode = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f01001c
			public const int scopeUris = 2130771996;
			
			// aapt resource value: 0x7f010007
			public const int uiCompass = 2130771975;
			
			// aapt resource value: 0x7f01000f
			public const int uiMapToolbar = 2130771983;
			
			// aapt resource value: 0x7f010008
			public const int uiRotateGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiScrollGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiTiltGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomControls = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int useViewLifecycle = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int zOrderOnTop = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040008
			public const int common_google_signin_btn_text_dark = 2130968584;
			
			// aapt resource value: 0x7f040000
			public const int common_google_signin_btn_text_dark_default = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int common_google_signin_btn_text_dark_disabled = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int common_google_signin_btn_text_dark_focused = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int common_google_signin_btn_text_dark_pressed = 2130968579;
			
			// aapt resource value: 0x7f040009
			public const int common_google_signin_btn_text_light = 2130968585;
			
			// aapt resource value: 0x7f040004
			public const int common_google_signin_btn_text_light_default = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int common_google_signin_btn_text_light_disabled = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int common_google_signin_btn_text_light_focused = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int common_google_signin_btn_text_light_pressed = 2130968583;
			
			// aapt resource value: 0x7f04000a
			public const int common_google_signin_btn_tint = 2130968586;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int activity_main = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int APROPOS3 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int APROPOS4 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int back_layout1 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int backActivity = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int backgroudApp = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int backInfo = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int backMain = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int backSimple = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int backTest = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int bb = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int bg = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int bnay = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int boGrid = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int bor = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int bordure = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int BordureNv = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int BorEnv = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int bt_back = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int btn = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_full_open_on_phone = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_google_signin_btn_icon_dark = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_google_signin_btn_icon_dark_focused = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_google_signin_btn_icon_dark_normal = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_google_signin_btn_icon_dark_normal_background = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_google_signin_btn_icon_disabled = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_google_signin_btn_icon_light = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_google_signin_btn_icon_light_focused = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_google_signin_btn_icon_light_normal = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_google_signin_btn_icon_light_normal_background = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_google_signin_btn_text_dark = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_google_signin_btn_text_dark_focused = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int common_google_signin_btn_text_dark_normal = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int common_google_signin_btn_text_dark_normal_background = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int common_google_signin_btn_text_disabled = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int common_google_signin_btn_text_light = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int common_google_signin_btn_text_light_focused = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int common_google_signin_btn_text_light_normal = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int common_google_signin_btn_text_light_normal_background = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int cup = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int dispo2 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int edit = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int envoyer = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int gardener = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int googleg_disabled_color_18 = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int googleg_standard_color_18 = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int greybackground = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int GridHead = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int GridHead2 = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int gridPng = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int hadad = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int halak = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int ic_launcher = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int Icon = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int icon1 = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int @in = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int inscr = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int inscrip = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int inscription = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int inscription2 = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int inTitle = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int jobb = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int k = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int left = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int linkedin = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int list_selector = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int ListViewBackground = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int location2 = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int login = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int loginn = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int loginPage = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int logo = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int mecanic = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int next = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int njar = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int pass = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int phone2 = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int plan = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int Plumber = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int pr_back = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int previous = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int profilH = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int profilH2 = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int profilHead = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int profilHead2 = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int profilHead3 = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int profill = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int Rechercher = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int registration = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int review = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int RoseButton = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int sebagh = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int seConnBack = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int seConnecterButton = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int select = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int semsar = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int SErviceB = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int serviceBack = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int serviceButton = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int ServicesBack = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int splash = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int starJ = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int starN = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int t1 = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int t2 = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int t3 = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int t4 = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int tick = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int tricien = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int txt_back = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int txtview_back = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int u = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int uD9js = 2130837616;
			
			// aapt resource value: 0x7f020071
			public const int user = 2130837617;
			
			// aapt resource value: 0x7f020072
			public const int usr = 2130837618;
			
			// aapt resource value: 0x7f020073
			public const int usrusr = 2130837619;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09004f
			public const int GridViewService = 2131296335;
			
			// aapt resource value: 0x7f09004c
			public const int Image = 2131296332;
			
			// aapt resource value: 0x7f09002e
			public const int NomEmp = 2131296302;
			
			// aapt resource value: 0x7f09002f
			public const int PreEmp = 2131296303;
			
			// aapt resource value: 0x7f090042
			public const int RecupTele = 2131296322;
			
			// aapt resource value: 0x7f09004d
			public const int Text = 2131296333;
			
			// aapt resource value: 0x7f09004e
			public const int Text1 = 2131296334;
			
			// aapt resource value: 0x7f090055
			public const int action1 = 2131296341;
			
			// aapt resource value: 0x7f090056
			public const int action2 = 2131296342;
			
			// aapt resource value: 0x7f09004b
			public const int add_scor = 2131296331;
			
			// aapt resource value: 0x7f090005
			public const int adjust_height = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int adjust_width = 2131296262;
			
			// aapt resource value: 0x7f090045
			public const int answerReset = 2131296325;
			
			// aapt resource value: 0x7f09000a
			public const int auto = 2131296266;
			
			// aapt resource value: 0x7f090043
			public const int b1 = 2131296323;
			
			// aapt resource value: 0x7f090039
			public const int btnConnection = 2131296313;
			
			// aapt resource value: 0x7f09002c
			public const int btnInscription = 2131296300;
			
			// aapt resource value: 0x7f090038
			public const int btnService = 2131296312;
			
			// aapt resource value: 0x7f090036
			public const int buRegister = 2131296310;
			
			// aapt resource value: 0x7f090035
			public const int bulogin = 2131296309;
			
			// aapt resource value: 0x7f09000f
			public const int chercheVille = 2131296271;
			
			// aapt resource value: 0x7f09000b
			public const int dark = 2131296267;
			
			// aapt resource value: 0x7f090015
			public const int drop_down_option_menu = 2131296277;
			
			// aapt resource value: 0x7f090054
			public const int email = 2131296340;
			
			// aapt resource value: 0x7f090041
			public const int envoyer = 2131296321;
			
			// aapt resource value: 0x7f09002b
			public const int etAdresse = 2131296299;
			
			// aapt resource value: 0x7f090025
			public const int etConfirmation = 2131296293;
			
			// aapt resource value: 0x7f090020
			public const int etNom = 2131296288;
			
			// aapt resource value: 0x7f090024
			public const int etPassword = 2131296292;
			
			// aapt resource value: 0x7f090021
			public const int etPrenom = 2131296289;
			
			// aapt resource value: 0x7f090023
			public const int etPseudo = 2131296291;
			
			// aapt resource value: 0x7f09002a
			public const int etReponse = 2131296298;
			
			// aapt resource value: 0x7f090022
			public const int etTelephone = 2131296290;
			
			// aapt resource value: 0x7f090033
			public const int etUsername = 2131296307;
			
			// aapt resource value: 0x7f090051
			public const int forgot_password = 2131296337;
			
			// aapt resource value: 0x7f09001d
			public const int gallery = 2131296285;
			
			// aapt resource value: 0x7f090011
			public const int header_cover_image = 2131296273;
			
			// aapt resource value: 0x7f090000
			public const int hybrid = 2131296256;
			
			// aapt resource value: 0x7f090007
			public const int icon_only = 2131296263;
			
			// aapt resource value: 0x7f090037
			public const int image1 = 2131296311;
			
			// aapt resource value: 0x7f09000d
			public const int imageView1 = 2131296269;
			
			// aapt resource value: 0x7f090030
			public const int imgEmp = 2131296304;
			
			// aapt resource value: 0x7f090032
			public const int left = 2131296306;
			
			// aapt resource value: 0x7f09000c
			public const int light = 2131296268;
			
			// aapt resource value: 0x7f09002d
			public const int linearLayout1 = 2131296301;
			
			// aapt resource value: 0x7f090010
			public const int listEmp = 2131296272;
			
			// aapt resource value: 0x7f09004a
			public const int mailR = 2131296330;
			
			// aapt resource value: 0x7f09003b
			public const int map = 2131296315;
			
			// aapt resource value: 0x7f090001
			public const int none = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int normal = 2131296258;
			
			// aapt resource value: 0x7f090047
			public const int password = 2131296327;
			
			// aapt resource value: 0x7f090014
			public const int phone = 2131296276;
			
			// aapt resource value: 0x7f090058
			public const int pm_repport = 2131296344;
			
			// aapt resource value: 0x7f090057
			public const int pm_update = 2131296343;
			
			// aapt resource value: 0x7f090013
			public const int profile_layout = 2131296275;
			
			// aapt resource value: 0x7f090044
			public const int questionReset = 2131296324;
			
			// aapt resource value: 0x7f090031
			public const int ratingEmp = 2131296305;
			
			// aapt resource value: 0x7f090034
			public const int recup = 2131296308;
			
			// aapt resource value: 0x7f090050
			public const int reg = 2131296336;
			
			// aapt resource value: 0x7f090048
			public const int repPassword = 2131296328;
			
			// aapt resource value: 0x7f090046
			public const int reset = 2131296326;
			
			// aapt resource value: 0x7f09001c
			public const int review = 2131296284;
			
			// aapt resource value: 0x7f090003
			public const int satellite = 2131296259;
			
			// aapt resource value: 0x7f09001f
			public const int scrollView1 = 2131296287;
			
			// aapt resource value: 0x7f090052
			public const int search = 2131296338;
			
			// aapt resource value: 0x7f090049
			public const int setPassword = 2131296329;
			
			// aapt resource value: 0x7f090053
			public const int share = 2131296339;
			
			// aapt resource value: 0x7f090029
			public const int spQuestion = 2131296297;
			
			// aapt resource value: 0x7f090027
			public const int spService = 2131296295;
			
			// aapt resource value: 0x7f09003d
			public const int spService1 = 2131296317;
			
			// aapt resource value: 0x7f090028
			public const int spVille = 2131296296;
			
			// aapt resource value: 0x7f09003e
			public const int spVille1 = 2131296318;
			
			// aapt resource value: 0x7f090008
			public const int standard = 2131296264;
			
			// aapt resource value: 0x7f09000e
			public const int sv = 2131296270;
			
			// aapt resource value: 0x7f09001e
			public const int te = 2131296286;
			
			// aapt resource value: 0x7f090004
			public const int terrain = 2131296260;
			
			// aapt resource value: 0x7f09003a
			public const int textView = 2131296314;
			
			// aapt resource value: 0x7f09003c
			public const int textView1 = 2131296316;
			
			// aapt resource value: 0x7f090026
			public const int textView2 = 2131296294;
			
			// aapt resource value: 0x7f090016
			public const int txtNom = 2131296278;
			
			// aapt resource value: 0x7f090040
			public const int txtPass = 2131296320;
			
			// aapt resource value: 0x7f09001b
			public const int txtPhoone = 2131296283;
			
			// aapt resource value: 0x7f090017
			public const int txtPrenom = 2131296279;
			
			// aapt resource value: 0x7f09003f
			public const int txtPseeudo = 2131296319;
			
			// aapt resource value: 0x7f090019
			public const int txtService = 2131296281;
			
			// aapt resource value: 0x7f09001a
			public const int txtVillee = 2131296282;
			
			// aapt resource value: 0x7f090018
			public const int user_profile_name = 2131296280;
			
			// aapt resource value: 0x7f090012
			public const int user_profile_photo = 2131296274;
			
			// aapt resource value: 0x7f090009
			public const int wide = 2131296265;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int google_play_services_version = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int aboutUs = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ChercherEmp = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DetaillsLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Inscription1 = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int listEmp = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int login = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int map = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int profil = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Recuperer = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Recuperer2 = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int recupperer3 = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Review = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int ServiceGrid = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int ServiceGridBackGround = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int SplashScrenn = 2130903055;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int menu_main = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int popupmenu = 2131230721;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050012
			public const int ApplicationName = 2131034130;
			
			// aapt resource value: 0x7f05001a
			public const int GoogleKey = 2131034138;
			
			// aapt resource value: 0x7f050011
			public const int Hello = 2131034129;
			
			// aapt resource value: 0x7f050016
			public const int action_1 = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int action_2 = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int action_3 = 2131034136;
			
			// aapt resource value: 0x7f050015
			public const int action_email = 2131034133;
			
			// aapt resource value: 0x7f050013
			public const int action_search = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int action_share = 2131034132;
			
			// aapt resource value: 0x7f050019
			public const int app_name = 2131034137;
			
			// aapt resource value: 0x7f050000
			public const int common_google_play_services_enable_button = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int common_google_play_services_enable_text = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int common_google_play_services_enable_title = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int common_google_play_services_install_button = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int common_google_play_services_install_text = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int common_google_play_services_install_title = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int common_google_play_services_notification_ticker = 2131034118;
			
			// aapt resource value: 0x7f050010
			public const int common_google_play_services_unknown_issue = 2131034128;
			
			// aapt resource value: 0x7f050007
			public const int common_google_play_services_unsupported_text = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int common_google_play_services_update_button = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int common_google_play_services_update_text = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int common_google_play_services_update_title = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int common_google_play_services_updating_text = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int common_google_play_services_wear_update_text = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int common_open_on_phone = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int common_signin_button_text = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int common_signin_button_text_long = 2131034127;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int MyActionBar = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int Theme_SplashActivity = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[] {
					2130771991,
					2130771992,
					2130771993};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 16
			public const int MapAttrs_ambientEnabled = 16;
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 18
			public const int MapAttrs_cameraMaxZoomPreference = 18;
			
			// aapt resource value: 17
			public const int MapAttrs_cameraMinZoomPreference = 17;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 21
			public const int MapAttrs_latLngBoundsNorthEastLatitude = 21;
			
			// aapt resource value: 22
			public const int MapAttrs_latLngBoundsNorthEastLongitude = 22;
			
			// aapt resource value: 19
			public const int MapAttrs_latLngBoundsSouthWestLatitude = 19;
			
			// aapt resource value: 20
			public const int MapAttrs_latLngBoundsSouthWestLongitude = 20;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			public static int[] SignInButton = new int[] {
					2130771994,
					2130771995,
					2130771996};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
